[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "1.0.6"
edition = "2021"
rust-version = "1.82"
license = "MIT"
authors = ["Yifan Yang <yfyang.86@hotmail.com>"]
repository = "https://github.com/yfyang86/tex2word"
homepage = "https://github.com/yfyang86/tex2word"
description = "LaTeX -> Microsoft Word (.docx) converter with native OMML math (Rust)"
keywords = ["latex", "docx", "ooxml", "converter", "math"]
categories = ["command-line-utilities", "text-processing"]

[profile.release]
opt-level = 3
lto = true
